In [1]:
import pandas as pd
import numpy as np
def JsonParser(data):
    import json
    js = json.loads(data)
    return js

df_list = pd.read_csv('listings.csv', converters={'amenities':JsonParser})
df_list.head(5)

C:\Users\manar\AppData\Local\Temp\ipykernel_19220\3374951888.py:8: DtypeWarning: Columns (68) have mixed types. Specify dtype option on import or set low_memory=False.
  df_list = pd.read_csv('listings.csv', converters={'amenities':JsonParser})

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2539,https://www.airbnb.com/rooms/2539,20220907064715,2022-09-07,city scrape,Clean & quiet apt home by the park,Renovated apt home in elevator building.<br />...,Close to Prospect Park and Historic Ditmas Park,https://a0.muscache.com/pictures/3949d073-a02e...,2787,...,5.00,4.75,4.88,NaN,f,9,1,6,2,0.11
1,2595,https://www.airbnb.com/rooms/2595,20220907064715,2022-09-07,city scrape,Skylit Midtown Castle,"Beautiful, spacious skylit studio in the heart...",Centrally located in the heart of Manhattan ju...,https://a0.muscache.com/pictures/f0813a11-40b2...,2845,...,4.80,4.81,4.40,NaN,f,3,3,0,0,0.31
2,5121,https://www.airbnb.com/rooms/5121,20220907064715,2022-09-07,city scrape,BlissArtsSpace!,One room available for rent in a 2 bedroom apt...,NaN,https://a0.muscache.com/pictures/2090980c-b68e...,7356,...,4.91,4.47,4.52,NaN,f,2,0,2,0,0.31
3,45910,https://www.airbnb.com/rooms/45910,20220907064715,2022-09-07,city scrape,Beautiful Queens Brownstone! - 5BR,"<b>The space</b><br />Beautiful, fully furnish...",NaN,https://a0.muscache.com/pictures/27117627/19ff...,204539,...,5.00,4.82,4.55,NaN,f,6,6,0,0,0.10
4,5136,https://www.airbnb.com/rooms/5136,20220907064715,2022-09-07,city scrape,"Spacious Brooklyn Duplex, Patio + Garden",We welcome you to stay in our lovely 2 br dupl...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,7378,...,5.00,4.67,5.00,NaN,f,1,1,0,0,0.03

In [2]:
df_list['room_type'].unique()

array(['Private room', 'Entire home/apt', 'Hotel room', 'Shared room'],
      dtype=object)

In [3]:
def xxx(row):
    cosmetics = ['conditioner', 'soap', 'shampoo']
    row = ['wifi' if 'wifi' in x.lower() else x.lower() for x in row] 
    row = ['childrens' if 'childrens' in x.lower() else x.lower() for x in row]
    row = ['tv' if 'tv' in x.lower() or 'hdtv' in x.lower()  else x.lower() for x in row]
    row = ['sound' if 'sound' in x.lower() else x.lower() for x in row]
    row = ['parking' if 'parking' in x.lower() else x.lower() for x in row]
    row = ['cosmetics' if any(cos in x for cos in cosmetics) else x.lower() for x in row]
    row = ['refrigerator' if 'refrigerator' in x.lower() else x.lower() for x in row]
    row = ['dryer' if 'dryer' in x.lower() else x.lower() for x in row]
    row = ['washer' if 'washer' in x.lower() else x.lower() for x in row]
    row = ['clothing' if 'clothing' in x.lower() else x.lower() for x in row]
    row = ['stove' if 'stove' in x.lower() else x.lower() for x in row]
    row = ['oven' if 'oven' in x.lower() else x.lower() for x in row]
    row = ['pool' if 'pool' in x.lower() else x.lower() for x in row]
    row = ['gym' if 'gym' in x.lower() else x.lower() for x in row]
    row = ['breakfast' if 'breakfast' in x.lower() else x.lower() for x in row]
    row = ['garage' if 'garage' in x.lower() else x.lower() for x in row]
    row = ['sauna' if 'sauna' in x.lower() else x.lower() for x in row]
    
    row = ['garden' if 'garden' in x.lower() else x.lower() for x in row]
    row = ['heating' if 'heating' in x.lower() else x.lower() for x in row]
    row = [x for x in row if x not in 'chair']
    row = ['hot tub' if 'hot tub' in x.lower() else x.lower() for x in row]
    row = ['console' if 'console' in x.lower() else x.lower() for x in row]
    row = ['conditioning' if 'conditioning' in x.lower() else x.lower() for x in row]
    row = ['high chair' if 'chair' in x.lower() else x.lower() for x in row] 
    #row = ['clamp on table seat high chair' if 'clamp' in x.lower() else x.lower() for x in row]
    row = ['pack n play/travel crib' if 'pack n play/travel crib' in x.lower() else x.lower() for x in row] 
    row = ['housekeeping' if 'housekeeping' in x.lower() else x.lower() for x in row] 
    row = ['free carport on premises' if 'free carport on premises' in x.lower() else x.lower() for x in row] 
    row = ['kitchen' if 'kitchen' in x.lower() else x.lower() for x in row]
    row = ['crib' if 'crib' in x.lower() else x.lower() for x in row]

In [4]:
def clear_amenities(row):
    to_clear = ['wifi','childrens','tv','sound','parking','refrigerator','dryer','washer','clothing','stove','oven','pool','gym','breakfast','garage','sauna','garden',
    'heating','hot tub','console','conditioning','chair','crib','housekeeping','free carport on premises','kitchen', 'ev charger', 'pillows', ' bar',  'fitness','restaurant']
    row = [x for x in row if x not in 'chair']
    cosmetics = ['conditioner', 'soap', 'shampoo', 'toiletries']
    sound = ['sound', 'speaker']
    row = ['cosmetics' if any(cos in x for cos in cosmetics) else x.lower() for x in row]
    row = ['sound' if any(cos in x for cos in sound) else x.lower() for x in row]
    for item in to_clear:
        row = [f'{item}' if f'{item}' in x.lower() else x.lower() for x in row]
    return row
    
def tv_size(row):
    for x in row:
        if('tv' in x.lower() or 'hdtv' in x.lower()):
            number = ''.join(filter(str.isdigit, x))
            if(number == ''):
                return -1
            else:
                return number
        else:
            return None

In [5]:
a=  ['childrens books and toys for ages 0-2 years old']
a = ['childrens' if 'childrens' in x.lower() else x.lower() for x in a]
a

['childrens']

In [6]:
#df_list['tv_size'] = df_list['amenities'].apply(tv_size)

#df_list['tv_size'] = df_list['amenities'].apply(tv_size)

In [7]:
def remove_weird_signs(row):
    row = [''.join([i if ord(i) < 128 else '' for i in x]) for x in row]
    row = [x.strip() for x in row]
    return row

In [8]:
df_list['amenities'] = df_list['amenities'].apply(remove_weird_signs)
df_list['amenities'] = df_list['amenities'].apply(clear_amenities)
items_list = df_list['amenities'].values.tolist()

In [9]:
result = pd.get_dummies(df_list['amenities'].apply(pd.Series).stack()).groupby(level=0).sum()
result

C:\Users\manar\AppData\Local\Temp\ipykernel_19220\3331405472.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  result = pd.get_dummies(df_list['amenities'].apply(pd.Series).stack()).groupby(level=0).sum()

,bar,ac - split type ductless system,airport shuttle,baby bath,baby monitor,baby safety gates,babysitter recommendations,backyard,baking sheet,barbecue utensils,...,toiletries,trash compactor,turndown service,tv,washer,waterfront,wifi,window ac unit,window guards,wine glasses
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,1,0,1,0,0,0
1,0,0,0,0,0,0,0,0,1,0,...,0,0,0,1,0,0,1,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,2,1,0,1,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,1,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39876,0,0,0,0,0,0,0,0,1,1,...,0,0,0,2,1,0,1,0,0,0
39877,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,1,0,0
39878,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
39879,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,2,1,1,0,0,1
39880,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [10]:
len(items_list)

39881

In [11]:
items_list = [item for sublist in items_list for item in sublist]
set_items_list = list(set(items_list))

In [12]:
pd.value_counts(items_list).sort_values().to_clipboard()

In [13]:
set_items_list

['cleaning before checkout',
 'outdoor furniture',
 'fireplace guards',
 'smoke alarm',
 'childrens',
 'beach essentials',
 'pour-over coffee',
 'ski-in/ski-out',
 'portable heater',
 'frette linens',
 'cooking basics',
 'iron',
 'waterfront',
 'parking',
 'kitchen',
 'garage',
 'essentials',
 'first aid kit',
 'mosquito net',
 'beach',
 'baking sheet',
 'security cameras on property',
 'bbq grill',
 'console',
 'concierge',
 'private patio or balcony',
 'babysitter recommendations',
 'laundromat nearby',
 'bidet',
 'bed linens',
 'cosmetics',
 'single level home',
 'tv',
 'bathtub',
 'mini fridge',
 'fire pit',
 'outlet covers',
 'pillows',
 'barbecue utensils',
 'baby bath',
 'garden',
 'airport shuttle',
 'wine glasses',
 'sauna',
 'house bikes',
 'turndown service',
 'hangers',
 'stove',
 'coffee maker',
 'host greets you',
 'bikes',
 'outdoor dining area',
 'ping pong table',
 'laundry services',
 'baby safety gates',
 'sound',
 'portable fans',
 'ceiling fan',
 'window ac unit',
 'rice maker',
 'lockbox',
 'room service',
 'garnier-thiebaut linens',
 'refrigerator',
 'wifi',
 'trash compactor',
 'nespresso machine',
 'fire extinguisher',
 'dryer',
 'private entrance',
 'baby monitor',
 'lake access',
 'kayak',
 'gym',
 'keypad',
 'room-darkening shades',
 'safe',
 'boat slip',
 'washer',
 'table corner guards',
 'outdoor shower',
 'conditioning',
 'toaster',
 'minibar',
 'hot water',
 'ev charger',
 'beachfront',
 'window guards',
 'indoor fireplace',
 'board games',
 'smart lock',
 'bottled water',
 'fitness',
 'spa',
 'dishes and silverware',
 'cleaning products',
 'chair',
 'piano',
 'ac - split type ductless system',
 'breakfast',
 'shared patio or balcony',
 'carbon monoxide alarm',
 'long term stays allowed',
 'shampoo',
 'hot tub',
 'bathrobes',
 'housekeeping',
 'dedicated workspace',
 'ethernet connection',
 'bread maker',
 'pool',
 'elevator',
 'building staff',
 'restaurant',
 'changing table',
 'lock on bedroom door',
 'luggage dropoff allowed',
 'steam room',
 'dining table',
 'freezer',
 'heating',
 'hot water kettle',
 'keurig coffee machine',
 'patio or balcony',
 'free carport on premises',
 'microwave',
 'conditioner',
 'backyard',
 'oven',
 ' bar',
 'crib',
 'sferra linens',
 'record player',
 'slippers',
 'toiletries',
 'shower gel',
 'clothing',
 'pets allowed']

In [14]:
jointed =  ' '.join(set_items_list)
jointed = jointed.split()

In [15]:
#pd.value_counts(jointed).sort_values().to_clipboard()